/classrooms:
  controller: Classrooms
  action: index
  method:
    - GET
/add-classroom:
  controller: Classrooms
  action: add
  method:
    - GET
/classrooms/:name/edit:
  controller: Classrooms
  action: edit
  params:
    - name: '[A-Za-z0-0]+'
  method:
    - GET
    - POST