/:
  controller: default
  action: default

/test/yves:
  controller: default
  action: default


/ajout-utilisateur:
  controller: "user"
  action: "add"

/utilisateur:
  controller: "user"
  action: "default"


/connexion:
  controller: "user"
  action: "login"










