/:
  controller: default
  action: default

/auth/register:
  controller: auth
  action: register

/auth/login:
  controller: auth
  action: login

/auth/forget-password:
  controller: auth
  action: forgetpassword

/dashboard:
  controller: dashboard
  action: index